#!/bin/sh
#
# Use this shell script to run your program on a test file.
#
# Use this script from a directory containing the executable "Main.class" and a
# subdirectory "tst" containing a file such as
#       test01.pcat
#
# Type:
#       go test01
#
# It will do the following:
#       Print the source file
#       Run "main"
#       Print the output file
#       Print the error output
#
echo --------------- Source tst/$f.pcat: ---------------
cat -n tst/$1.pcat | more
java Main < tst/$1.pcat 1> tst/$1.out 2> tst/$1.err
echo --------------- Output stdout: ---------------
more tst/$1.out
echo --------------- Error output stderr: ---------------
more tst/$1.err
rm tst/$1.out
rm tst/$1.err
