#!/bin/sh
#
# Use this shell script to test your program.
#
# Use this script from a directory that contains the "*.class" files and a
# subdirectory "tst" containing files such as
#	test1.e
#	test1.out.bak
#	test1.err.bak
#
# Type:
#	run test1
#
# It will first run "main" to create files:
#	test1.out
#	test1.err
#
# It will then print any differences between your output/error files
# and the pre-existing ".bak" output/error files.
#
echo $1:
java Proj1 tst/$1.e 1> tst/$1.out 2> tst/$1.err
diff -w tst/$1.out.bak tst/$1.out
diff -w tst/$1.err.bak tst/$1.err
rm tst/$1.out
rm tst/$1.err
